# Generated by Django 4.1.4 on 2023-08-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchangeID', models.CharField(default='', max_length=255)),
                ('exchangeName', models.CharField(default='', max_length=255)),
                ('currency', models.CharField(choices=[('CAD', 'Cad'), ('USD', 'Usd')], max_length=30)),
                ('country', models.CharField(choices=[('CANADA', 'Canada'), ('USA', 'Usa')], max_length=30)),
            ],
        ),
    ]
